### ISSUE TITLE
Get "invalid resource" when acquire token by german office 365 account

### ISSUE THREAD

**Issue by verybada** [OneDrive/onedrive-sdk-python#113]
Hi,

I got error `invalid resource` during execute sample code (I had already change endpoint to .de, please see following snippet). Should I use different resource for German 365?
```
127.0.0.1 - - [02/Aug/2017 14:08:04] "GET /?code=AQABAAIAAQDnLpu3ikefR73l... HTTP/1.1" 200 -
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    auth.authenticate(code, redirect_uri, client_secret, resource=discovery_uri)
  File "/Users/verybada/workspace/vm/venv/lib/python2.7/site-packages/onedrivesdk/auth_provider.py", line 203, in authenticate
    data=params)
  File "/Users/verybada/workspace/vm/venv/lib/python2.7/site-packages/onedrivesdk/http_provider.py", line 71, in send
    custom_response = HttpResponse(response.status_code, response.headers, response.text)
  File "/Users/verybada/workspace/vm/venv/lib/python2.7/site-packages/onedrivesdk/http_response.py", line 61, in __init__
    raise Exception(str(message["error"]))
Exception: invalid_resource
```

```
import onedrivesdk
from onedrivesdk.helpers import GetAuthCodeServer
from onedrivesdk.helpers.resource_discovery import ResourceDiscoveryRequest

redirect_uri = 'http://localhost'
client_id = $id
client_secret = $secret
discovery_uri = 'https://api.office.com/discovery/'
auth_server_url='https://login.microsoftonline.de/common/oauth2/authorize'
auth_token_url='https://login.microsoftonline.de/common/oauth2/token'

http = onedrivesdk.HttpProvider()
auth = onedrivesdk.AuthProvider(http,
                                client_id,
                                auth_server_url=auth_server_url,
                                auth_token_url=auth_token_url)
auth_url = auth.get_auth_url(redirect_uri)
code = GetAuthCodeServer.get_auth_code(auth_url, redirect_uri)
auth.authenticate(code, redirect_uri, client_secret, resource=discovery_uri)
# If you have access to more than one service, you'll need to decide
# which ServiceInfo to use instead of just using the first one, as below.
service_info = ResourceDiscoveryRequest().get_service_info(auth.access_token)[0]
auth.redeem_refresh_token(service_info.service_resource_id)
print service_info.service_resource_id
client = onedrivesdk.OneDriveClient(service_info.service_resource_id + '/_api/v2.0/', auth, http)
```

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
