### ISSUE TITLE
upload_async fails in < python 3.6

### ISSUE THREAD

**Issue by gojohnkevin** [OneDrive/onedrive-sdk-python#114]
I have a file worth 600mb. Tried using python 3.6, upload_sync works well but tried on python 3.5.3, it fails.

`{'error': 'invalid_request', 'error_description': 'This access token is not valid on this endpoint.'}`

Here's the traceback:
`Traceback (most recent call last):
  File "/home/keving/.pyenv/versions/3.5.3/lib/python3.5/site-packages/onedriveb_cli/actions.py", line 195, in upload
    uploaded_item = client.item(drive=drive, id=resource_id).children[cleaned_filename].upload_async(file)
  File "/home/keving/.pyenv/versions/3.5.3/lib/python3.5/site-packages/onedrivesdk/version_bridge/fragment_upload.py", line 173, in fragment_upload_async
    resp = upload_builder.post(i * __PART_SIZE, length)
  File "/home/keving/.pyenv/versions/3.5.3/lib/python3.5/site-packages/onedrivesdk/version_bridge/fragment_upload.py", line 121, in post
    return self.request(begin, length, options).post()
  File "/home/keving/.pyenv/versions/3.5.3/lib/python3.5/site-packages/onedrivesdk/version_bridge/fragment_upload.py", line 57, in post
    entity = UploadSession(json.loads(self.send(data=self._file_handle).content))
  File "/home/keving/.pyenv/versions/3.5.3/lib/python3.5/site-packages/onedrivesdk/request_base.py", line 151, in send
    data=data)
  File "/home/keving/.pyenv/versions/3.5.3/lib/python3.5/site-packages/onedrivesdk/http_provider.py", line 71, in send
    custom_response = HttpResponse(response.status_code, response.headers, response.text)
  File "/home/keving/.pyenv/versions/3.5.3/lib/python3.5/site-packages/onedrivesdk/http_response.py", line 62, in __init__
    raise Exception(str(message["error"]))
Exception: invalid_request`

**Comment by KTibow** [comment]
@gojohnkevin #116 mentions that it closes this. Update your library and try again. If it's fixed, consider closing.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
