### ISSUE TITLE
Download and upload whole folder from one drive personal

### ISSUE THREAD

**Issue by hoangvietfreelancer** [OneDrive/onedrive-sdk-python#144]
I want to download and upload a folder from onedrive to my pc using linux. How can i do that?

**Comment by KTibow** [comment]
@hoangvietfreelancer I don't know if there's another way to do this, but as long as your folder doesn't have folders inside it, you could probably download/upload each file individually. I store my files as `.zip`s myself to save space, and zip before uploading. You can get a link for a folder successfully.
If I try to do a normal download for a whole folder, I get this message:
```
Traceback (most recent call last):
  File "<pyshell#7>", line 1, in <module>
    hi.download("/home/pi/webby")
  File "/usr/local/lib/python3.7/dist-packages/onedrivesdk/request/item_request_builder.py", line 138, in download
    return self.content.request().download(local_path)
  File "/usr/local/lib/python3.7/dist-packages/onedrivesdk/request/item_content_request.py", line 88, in download
    self.download_item(content_local_path)
  File "/usr/local/lib/python3.7/dist-packages/onedrivesdk/request_base.py", line 188, in download_item
    path)
  File "/usr/local/lib/python3.7/dist-packages/onedrivesdk/http_provider.py", line 100, in download
    custom_response = HttpResponse(response.status_code, response.headers, response.text)
  File "/usr/local/lib/python3.7/dist-packages/onedrivesdk/http_response.py", line 59, in __init__
    raise OneDriveError(message["error"], self.status)
onedrivesdk.error.OneDriveError: itemNotFound - The specified item does not have content.
```
Consider closing if it makes sense. Your issue is old, so probably the only reason you'd want to leave this open is if it would help the community.
Also, so I can try to help you more: What folder are you trying to upload/download?

**Comment by hoangvietfreelancer** [comment]
Sorry for the inconvenience. I forgot this issue so I didn't close it.
