### ISSUE TITLE
Auth issue

### ISSUE THREAD

**Issue by etalot** [OneDrive/onedrive-sdk-python#146]
Auth issue:

```Traceback (most recent call last):
  File "CommandLineFileExplorer.py", line 167, in <module>
    main()
  File "CommandLineFileExplorer.py", line 28, in main
    client.auth_provider.authenticate(code, redirect_uri, client_secret)
  File "/usr/local/lib/python2.7/dist-packages/onedrivesdk/auth_provider.py", line 202, in authenticate
    data=params)
  File "/usr/local/lib/python2.7/dist-packages/onedrivesdk/http_provider.py", line 71, in send
    custom_response = HttpResponse(response.status_code, response.headers, response.text)
  File "/usr/local/lib/python2.7/dist-packages/onedrivesdk/http_response.py", line 61, in __init__
    raise Exception(str(message["error"]))
Exception: invalid_request```

**Comment by KTibow** [comment]
You're using Python 2, @etalot. Try running this in Python 3. Also make sure you replaced the default client ID and Secret. (You can get them at https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationsListBlade)

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
