### ISSUE TITLE
Clearer errors when a field is required

### ISSUE THREAD

**Issue by cdmayer** [OneDrive/onedrive-sdk-python#15]
``` python
session = client.item(drive="me", path="backup/test_file").create_session().post()
```

Gives a boneheaded stack trace:

``` python
Traceback (most recent call last):
  File "create-session.py", line 34, in <module>
    session = client.item(drive="me", path="backupy/test_file").create_session().post()
  File "/home/w/python/onedrive/venv/lib/python3.4/site-packages/onedrivesdk-1.0.1-py3.4.egg/onedrivesdk/request/item_request_builder.py", line 229, in create_session
    return ItemCreateSessionRequestBuilder(self.append_to_request_url("upload.createSession"), self._client, item=item)
  File "/home/w/python/onedrive/venv/lib/python3.4/site-packages/onedrivesdk-1.0.1-py3.4.egg/onedrivesdk/request/item_create_session.py", line 84, in __init__
    self._method_options["item"] = item._prop_dict
AttributeError: 'NoneType' object has no attribute '_prop_dict'
```

It's because `create_session()` actually requires an `Item`. This probably shows up in other places too. Make sure that is clear by throwing an error when an `Item` is not provided.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
