### ISSUE TITLE
Can't upload file

### ISSUE THREAD

**Issue by KTibow** [OneDrive/onedrive-sdk-python#171]
I'm trying to upload a file (it might be a bit large, but it's not giant) and I get this error:
Traceback (most recent call last):
  File "/home/pi/backup.py", line 35, in <module>
    returned_item = client.item(drive='me', id='root').children['backup'+str(time())+".zip"].upload('./backup.zip')
  File "/home/pi/.local/lib/python3.7/site-packages/onedrivesdk/request/item_request_builder.py", line 117, in upload
    return self.content.request().upload(local_path)
  File "/home/pi/.local/lib/python3.7/site-packages/onedrivesdk/request/item_content_request.py", line 60, in upload
    entity = Item(json.loads(entity_response.content))
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Do you know what the source of this is?

**Comment by KTibow** [comment]
Looking at the stack trace a bit more, I see that I think it uploaded it but it wasn't able to parse the response.

**Comment by KTibow** [comment]
I can manually upload it just fine. If I look at the files, I think it wasn't able to complete a finalization step or something, because the program uploaded version doesn't work.

**Comment by KTibow** [comment]
The solution to #32 worked. Can you add a progress indicator please, though?

**Comment by KTibow** [comment]
Found the progress indicator.
