### ISSUE TITLE
Auth Business: cannot get anything at ResourceDiscoveryRequest().get_service_info

### ISSUE THREAD

**Issue by cnbeining** [OneDrive/onedrive-sdk-python#60]
I am trying to add support to Business.

This is what I am trying to do:

```
import onedrivesdk
http = onedrivesdk.HttpProvider()
auth = onedrivesdk.AuthProvider(http,
                                client_id_business ,
                                auth_server_url=auth_server_url,
                                auth_token_url=auth_token_url)

auth_url = auth.get_auth_url(redirect_uri)

(Open the URL at the browse and get the code)

auth.authenticate(code, redirect_uri, client_secret, resource= 'https://api.office.com/discovery/')

```

Then 

```
ResourceDiscoveryRequest().get_service_info(auth.access_token)
```

is returning empty list.

A manual trial with curl is showing:

```
curl -H "Authorization: Bearer {access_token_got_with_auth.access_token}" "https://api.office.com/discovery/v2.0/me/services" -k

{"@odata.context":"https://api.office.com/discovery/v2.0/me/$metadata#allServices","value":[]}
```

I am trying the graph API with the same access token, but received such error:

```
{
  "error": {
    "code": "InvalidAuthenticationToken",
    "message": "Access token validation failure.",
    "innerError": {
      "request-id": "82f68338-83ae-4659-9135-161ad1b399fd",
      "date": "2016-09-26T18:49:01"
    }
  }
}
```

And I cannot use graph SDK due to

```
>>> import msgraph
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/msgraph/__init__.py", line 96, in <module>
    from .request.directory_object_request_builder import DirectoryObjectRequestBuilder
  File "/usr/local/lib/python2.7/site-packages/msgraph/request/directory_object_request_builder.py", line 11, in <module>
    from ..request.directory_object_check_member_groups import DirectoryObjectCheckMemberGroupsRequestBuilder
  File "/usr/local/lib/python2.7/site-packages/msgraph/request/directory_object_check_member_groups.py", line 12, in <module>
    from ..request import drive_item_collection 
  File "/usr/local/lib/python2.7/site-packages/msgraph/request/drive_item_collection.py", line 11, in <module>
    from ..request import drive_item_request_builder # import DriveItemRequestBuilder
  File "/usr/local/lib/python2.7/site-packages/msgraph/request/drive_item_request_builder.py", line 12, in <module>
    from ..request.drive_item_search import DriveItemSearchRequestBuilder
  File "/usr/local/lib/python2.7/site-packages/msgraph/request/drive_item_search.py", line 13, in <module>
    from ..request import drive_item_collection 
ImportError: cannot import name drive_item_collection
```

Where did I do wrong?

Many thanks.

**Comment by cdmayer** [comment]
If you didn't get any services back in the endpoint discovery response, you probably haven't authorized the app for appropriate scopes. Check out the [authentication documentation](https://dev.onedrive.com/app-registration.htm#3-register-your-app-with-azure-active-directory).

**Comment by ybizeul** [comment]
I think I have a similar issue, just slap me in the face if I should create my own issue.

```
Traceback (most recent call last):
  File "corporate.py", line 23, in <module>
    service_info = ResourceDiscoveryRequest().get_service_info(auth.access_token)[0]
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/onedrivesdk-1.1.6-py3.5.egg/onedrivesdk/helpers/resource_discovery.py", line 26, in get_service_info
    service_info_list = [ServiceInfo(x) for x in response['value']]
KeyError: 'value'
```

I set `resource`to `https://mycompany-my.sharepoint.com` but I don't exactly understand what this error means, that 'value' isn't a key in the result? That the array is empty?

My application is registered and in "Microsoft Graph Permissions" I added Files.ReadWrite.All in **Delegated Permissions** but I have no access to add anything to **Application Permissions**, is that the problem?

**Comment by cnbeining** [comment]
My solution: 

It could be some permission issues of programme. Try start with every permission and remove one by one.

**Comment by ybizeul** [comment]
I know, here is what I get when I try to set permissions for my application.

Basically what I'm doing is a script that needs to upload files to my OneDrive (and just mine, I'm not interacting with other members, it's a personal thing). I'm not sure I can do that through the APIs without corporate validation (Admin Only thing?):

<img width="686" alt="screen shot 2016-10-31 at 5 53 20 pm" src="https://cloud.githubusercontent.com/assets/182035/19873003/f728e346-9f92-11e6-9ee7-aea1314de15b.png">

**Comment by ybizeul** [comment]
I manually printed the `response` object and here is what I get :

```
{'error': {'message': 'Access denied. You do not have permission to perform this action or access this resource.', 'code': '-2147024891, System.UnauthorizedAccessException'}}
```

Should I point to a resource specific to my OneDrive folder? Is there even a way to do that?

**Comment by cnbeining** [comment]
I am not sure this SDK would works with the Graph API though...it's pretty painful for now.

**Comment by cdmayer** [comment]
I think I spotted a hole in the docs. Can you try setting `resource='https://api.office.com/discovery/'` before you call the discovery service? That's the place where you ask, "to what resources does this user have access?" _That_ should point you to your SharePoint tenant. Please let me know how that goes.

**Comment by ybizeul** [comment]
Not sure how to do this.
I tried calling :

```
service_info = ResourceDiscoveryRequest().get_service_info('https://api.office.com/discovery/')[0]
```

instead of :

```
service_info = ResourceDiscoveryRequest().get_service_info(auth.access_token)[0]
```

And I also tried to do it directly in `resource_discovery.py` :

```
        access_token='https://api.office.com/discovery/'
```

But I get the same result :

```
{'error': {'code': '-2147024891, System.UnauthorizedAccessException', 'message': 'Access denied. You do not have permission to perform this action or access this resource.'}}
Traceback (most recent call last):
  File "corporate.py", line 23, in <module>
    service_info = ResourceDiscoveryRequest().get_service_info('https://api.office.com/discovery/')[0]
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/onedrivesdk-1.1.6-py3.5.egg/onedrivesdk/helpers/resource_discovery.py", line 27, in get_service_info
    service_info_list = [ServiceInfo(x) for x in response['value']]
KeyError: 'value'
```

I get the same error if I simply set :

```
resource='https://api.office.com/discovery/'
```

Here is the error :

```
{'error': {'message': 'Access denied. You do not have permission to perform this action or access this resource.', 'code': '-2147024891, System.UnauthorizedAccessException'}}
Traceback (most recent call last):
  File "corporate.py", line 24, in <module>
    service_info = ResourceDiscoveryRequest().get_service_info('https://api.office.com/discovery/')[0]
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/onedrivesdk-1.1.6-py3.5.egg/onedrivesdk/helpers/resource_discovery.py", line 27, in get_service_info
    service_info_list = [ServiceInfo(x) for x in response['value']]
KeyError: 'value'
```

**Comment by cdmayer** [comment]
Can you please just paste in all your code? That will be easier to diagnose.

**Comment by cnbeining** [comment]
https://github.com/cnbeining/onedrivecmd/blob/master/utils/actions.py#L20-L73 https://github.com/cnbeining/onedrivecmd/blob/master/utils/actions.py#L20-L73

Could help you with this issue.

**Comment by ybizeul** [comment]
```
import onedrivesdk
from onedrivesdk.helpers import GetAuthCodeServer
from onedrivesdk.helpers.resource_discovery import ResourceDiscoveryRequest

redirect_uri = 'http://localhost:8080/'
client_id = 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
client_secret = 'xxxxxxxxxxxxxxxxxxxxxxx'
discovery_uri = 'https://api.office.com/discovery/'
auth_server_url='https://login.microsoftonline.com/common/oauth2/authorize'
auth_token_url='https://login.microsoftonline.com/common/oauth2/token'
resource='https://xxxxxxx-my.sharepoint.com/'
#resource='https://api.office.com/discovery/'

http = onedrivesdk.HttpProvider()
auth = onedrivesdk.AuthProvider(http,
                                client_id,
                                auth_server_url=auth_server_url,
                                auth_token_url=auth_token_url)
auth_url = auth.get_auth_url(redirect_uri)
code = GetAuthCodeServer.get_auth_code(auth_url, redirect_uri)
auth.authenticate(code, redirect_uri, client_secret, resource=resource)
# If you have access to more than one service, you'll need to decide
# which ServiceInfo to use instead of just using the first one, as below.
service_info = ResourceDiscoveryRequest().get_service_info('https://api.office.com/discovery/')[0]
auth.redeem_refresh_token(service_info.service_resource_id)
client = onedrivesdk.OneDriveClient(service_info.service_resource_id + '/_api/v2.0/', auth, http)
```

**Comment by cdmayer** [comment]
You'll definitely want `auth.authenticate(code, redirect_uri, client_secret, resource=discovery_uri)`

Do you get any results from `ResourceDiscoveryRequest`?

**Comment by ybizeul** [comment]
There you go :

```
[...]
resource='https://mycompany-my.sharepoint.com/'
[...]
auth.authenticate(code, redirect_uri, client_secret, resource=discovery_uri)
[...]
service_info = ResourceDiscoveryRequest().get_service_info(resource)[0]
```

At `ResourceDiscoveryRequest`, it throws :

```
{'error': {'code': '-2147024891, System.UnauthorizedAccessException', 'message': 'Access denied. You do not have permission to perform this action or access this resource.'}}
Traceback (most recent call last):
  File "corporate.py", line 24, in <module>
    service_info = ResourceDiscoveryRequest().get_service_info(resource)[0]
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/onedrivesdk-1.1.6-py3.5.egg/onedrivesdk/helpers/resource_discovery.py", line 27, in get_service_info
    service_info_list = [ServiceInfo(x) for x in response['value']]
KeyError: 'value'
```

**Comment by ybizeul** [comment]
By the way I feel like hijacking @cnbeining issue, should I open a separate issue or is this related?

**Comment by cdmayer** [comment]
> `service_info = ResourceDiscoveryRequest().get_service_info(resource)[0]`

You need to pass in the auth token, not the resource. That line should be:

> `service_info = ResourceDiscoveryRequest().get_service_info(auth.access_token)[0]`

Just like in the sample code.

**Comment by cdmayer** [comment]
It sounds like @cnbeining 's issue has been resolved

**Comment by cnbeining** [comment]
Yeah my issue was resolved. Feel free to close or continue this thread since it is the same issue.

**Comment by cnbeining** [comment]
@ybizeul I do suggest that you look into my solution and see how it works.

**Comment by ybizeul** [comment]
@cnbeining Thanks, I tried to open a bit and reach other item I thought I didn't need, but not helping much. What level did you add privilege when you look at my screenshot above, delegated or application?

I actually fixed that resource part of the code now, there was a lot of confusion on my side so it's "better" now, sorry about that @cdmayer :

```
{'value': [], '@odata.context': 'https://api.office.com/discovery/v2.0/me/$metadata#allServices'}
Traceback (most recent call last):
  File "corporate.py", line 24, in <module>
    service_info = ResourceDiscoveryRequest().get_service_info(auth.access_token)[0]
IndexError: list index out of range
```

So the returned array is empty.

**Comment by D4N14L** [comment]
Closing out since the issue seems solved. Thanks!

**Comment by hsyang76** [comment]
@ybizeul, Have you solved "list index out of range" issue?
