### ISSUE TITLE
Error in updating subscription

### ISSUE THREAD

**Issue by xybu** [OneDrive/onedrive-sdk-python#95]
It seems that `SubscriptionRequest` is a subclass of `RequestBase` but the method `_initialize_collection_properties` is in `ItemRequest` class (which is also a subclass of `RequestBase`). Calling `SubscriptionRequest._initialize_collection_properties()` in places such as https://github.com/OneDrive/onedrive-sdk-python/blob/8a406a0769f75a96eda8ffd0a530c18695dbe96d/src/python3/request/subscription_request.py#L80 will throw an exception. There are a few more places like this in `SubscriptionRequest`. Or am I using the SDK wrong?

My usage (simplified):

```
item_request = client.item(path='/')
subscription = onedrivesdk.Subscription()
subscription.notification_url = some_url
subscription.expiration_date_time = expiration_time
item_request.subscriptions[some_subscription_id].update(subscription)
```

Stack trace (excerpt):

```
[2017-01-23 02:13:39,720] DEBUG: MainThread: https://api.onedrive.com:443 "PATCH /v1.0/drives/d781730a6d2c6611/root:/:/subscriptions/WLS_SubscriptionId_8130F4E6-E624-4E09-A630-7AB2E8793666 HTTP/1.1" 200 455

...
Traceback (most recent call last):
...
  File "/usr/local/lib/python3.5/dist-packages/onedrivesdk/request/subscription_request_builder.py", line 84, in update
    return self.request().update(subscription)
  File "/usr/local/lib/python3.5/dist-packages/onedrivesdk/request/subscription_request.py", line 80, in update
    self._initialize_collection_properties(entity)
AttributeError: 'SubscriptionRequest' object has no attribute '_initialize_collection_properties'
```

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
